export enum RolesPermissions {
  CREATE_GENRES = "CREATE_GENRES",
  UPDATE_GENRES = "UPDATE_GENRES",
  MANAGE_ROLES = "MANAGE_ROLES",
  CREATE_AUTHORS = "CREATE_AUTHORS",
  UPDATE_AUTHORS = "UPDATE_AUTHORS",
  CREATE_BOOKS = "CREATE_BOOKS",
  UPDATE_BOOKS = "UPDATE_BOOKS",
}
export const MainAdmin = "Main-Admin";
